# H2 Console
h2:
console:
enabled: true
path: /h2-console
# DB Settings
datasource:
driver-class-name: org.h2.Driver
url: jdbc:h2:mem:test
username: sa
password:

logging:
  level:
    org:
      springframework:
        security: debug

auth:
  jwt:
    issuer: team.sparta.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 168

external:
  data4library:
    secretKey: ${Data4Lib_Secret_Key}
  kakao:
    restApiKey: ${Kakao_RestApi_Key}
  naver:
    clientId: ${Naver_Client_Id}
    clientSecret: ${Naver_Client_Secret}