--- # dev
spring:
  config:
    activate:
      on-profile: "db-dev"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create

--- # prod
spring:
  config:
    activate:
      on-profile: "db-prod"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_ID}
    password: ${POSTGRES_PW}
  jpa:
    hibernate:
      ddl-auto: validate